# Copyright (c) 2025, aminos and contributors
# For license information, please see license.txt

import frappe


def execute(filters=None):
    """
    Main function that runs when the report is generated.
    """
    columns = get_columns()
    data = get_data(filters)

    # The chart data is generated by the JS file, so we just return columns and data.
    return columns, data


def get_columns():
    """Defines the columns for the report's data table."""
    return [
        {"label": "Timestamp", "fieldname": "log_timestamp",
            "fieldtype": "Datetime", "width": 160},
        {"label": "Hydroponic System", "fieldname": "hydroponic_system",
            "fieldtype": "Link", "options": "Asset", "width": 180},
        {"label": "Measured pH", "fieldname": "measured_ph",
            "fieldtype": "Float", "width": 120},
        {"label": "Measured EC (mS/cm)", "fieldname": "measured_ec_mscm",
         "fieldtype": "Float", "width": 160},
        {"label": "Water Temp (°C)", "fieldname": "water_temperature_c",
         "fieldtype": "Float", "width": 150},
        {"label": "Notes", "fieldname": "general_notes",
            "fieldtype": "Data", "width": 200},
    ]


def get_data(filters):
    """Fetches the data from the database based on the provided filters."""
    conditions = ""
    filter_values = {}

    # Apply filters if they are provided by the user
    if filters.get("hydroponic_system"):
        conditions += " AND hydroponic_system = %(hydroponic_system)s"
        filter_values["hydroponic_system"] = filters["hydroponic_system"]

    if filters.get("date_range"):
        start_date, end_date = filters["date_range"]
        # Use log_timestamp for date filtering
        conditions += " AND DATE(log_timestamp) BETWEEN %(start_date)s AND %(end_date)s"
        filter_values["start_date"] = start_date
        filter_values["end_date"] = end_date

    # Fetch data using frappe.db.sql and your exact fieldnames
    data = frappe.db.sql(f"""
        SELECT
            log_timestamp,
            hydroponic_system,
            measured_ph,
            measured_ec_mscm,
            water_temperature_c,
            general_notes
        FROM
            `tabWater Quality Log`
        WHERE 1=1 -- Start with a true condition to easily append more
        {conditions}
        ORDER BY
            log_timestamp ASC
    """, filter_values, as_dict=True)

    return data
