itemgroups = [
    {"item_group_name": "Agriculture Items Group", "is_group": 1},
    {"item_group_name": "Fertilizer", "is_group": 0,
        "parent_item_group": "Agriculture Items Group"},
    {"item_group_name": "Seeds", "is_group": 0,
        "parent_item_group": "Agriculture Items Group"},
    {"item_group_name": "By Product", "is_group": 0,
        "parent_item_group": "Agriculture Items Group"},
    {"item_group_name": "Produce", "is_group": 0,
        "parent_item_group": "Agriculture Items Group"},
    {"item_group_name": "Greenhouse Structures", "is_group": 0,
        "parent_item_group": "Agriculture Items Group"},

    # Livestock
    {"item_group_name": "Livestock", "is_group": 1},

    # Live Animals
    {"item_group_name": "Live Animals", "is_group": 1,
        "parent_item_group": "Livestock"},
    {"item_group_name": "Cattle", "is_group": 0,
        "parent_item_group": "Live Animals"},
    {"item_group_name": "Buffalo", "is_group": 0,
        "parent_item_group": "Live Animals"},
    {"item_group_name": "Sheep", "is_group": 0,
        "parent_item_group": "Live Animals"},
    {"item_group_name": "Goat", "is_group": 0,
        "parent_item_group": "Live Animals"},
    {"item_group_name": "Horse", "is_group": 0,
        "parent_item_group": "Live Animals"},
    {"item_group_name": "Camel", "is_group": 0,
        "parent_item_group": "Live Animals"},
    {"item_group_name": "Rabbit", "is_group": 0,
        "parent_item_group": "Live Animals"},
    {"item_group_name": "Poultry", "is_group": 1,
        "parent_item_group": "Live Animals"},
    {"item_group_name": "Chicken", "is_group": 0, "parent_item_group": "Poultry"},
    {"item_group_name": "Duck", "is_group": 0, "parent_item_group": "Poultry"},
    {"item_group_name": "Goose", "is_group": 0, "parent_item_group": "Poultry"},
    {"item_group_name": "Turkey", "is_group": 0, "parent_item_group": "Poultry"},

    # Animal Products
    {"item_group_name": "Animal Products",
        "is_group": 1, "parent_item_group": "Livestock"},
    {"item_group_name": "Meat", "is_group": 0,
        "parent_item_group": "Animal Products"},
    {"item_group_name": "Milk", "is_group": 0,
        "parent_item_group": "Animal Products"},
    {"item_group_name": "Eggs", "is_group": 0,
        "parent_item_group": "Animal Products"},
    {"item_group_name": "Wool", "is_group": 0,
        "parent_item_group": "Animal Products"},
    {"item_group_name": "Hides & Leather", "is_group": 0,
        "parent_item_group": "Animal Products"},
    {"item_group_name": "Fiber", "is_group": 0,
        "parent_item_group": "Animal Products"},

    # Livestock Consumables
    {"item_group_name": "Livestock Consumables", "is_group": 1},
    {"item_group_name": "Animal Feed", "is_group": 1,
        "parent_item_group": "Livestock Consumables"},
    {"item_group_name": "Base Feeds", "is_group": 0,
        "parent_item_group": "Animal Feed"},
    {"item_group_name": "Forage", "is_group": 0,
        "parent_item_group": "Animal Feed"},
    {"item_group_name": "Supplements", "is_group": 0,
        "parent_item_group": "Animal Feed"},
    {"item_group_name": "Veterinary Medicine", "is_group": 1,
        "parent_item_group": "Livestock Consumables"},
    {"item_group_name": "Vaccines", "is_group": 0,
        "parent_item_group": "Veterinary Medicine"},
    {"item_group_name": "Antibiotics", "is_group": 0,
        "parent_item_group": "Veterinary Medicine"},
    {"item_group_name": "Dewormers", "is_group": 0,
        "parent_item_group": "Veterinary Medicine"},

    # Hydroponics
    {"item_group_name": "Hydroponic Equipment", "is_group": 1,
        "parent_item_group": "Agriculture Items Group"},
    {"item_group_name": "Grow Trays & Channels", "is_group": 0,
        "parent_item_group": "Hydroponic Equipment"},
    {"item_group_name": "Nutrient Film Technique (NFT) Systems",
     "is_group": 0, "parent_item_group": "Hydroponic Equipment"},
    {"item_group_name": "Deep Water Culture (DWC) Systems",
     "is_group": 0, "parent_item_group": "Hydroponic Equipment"},
    {"item_group_name": "Aeroponic Systems", "is_group": 0,
        "parent_item_group": "Hydroponic Equipment"},
    {"item_group_name": "Drip Irrigation Systems", "is_group": 0,
        "parent_item_group": "Hydroponic Equipment"},
    {"item_group_name": "Grow Lights", "is_group": 0,
        "parent_item_group": "Hydroponic Equipment"},
    {"item_group_name": "Nutrient Solutions", "is_group": 0,
        "parent_item_group": "Hydroponic Equipment"},
    {"item_group_name": "pH & EC Meters", "is_group": 0,
        "parent_item_group": "Hydroponic Equipment"},
    {"item_group_name": "Water Pumps & Air Pumps", "is_group": 0,
        "parent_item_group": "Hydroponic Equipment"},
    {"item_group_name": "Growing Media", "is_group": 1,
        "parent_item_group": "Hydroponic Equipment"},
    {"item_group_name": "Coco Coir", "is_group": 0,
        "parent_item_group": "Growing Media"},
    {"item_group_name": "Rockwool", "is_group": 0,
        "parent_item_group": "Growing Media"},
    {"item_group_name": "Perlite & Vermiculite",
        "is_group": 0, "parent_item_group": "Growing Media"},
    {"item_group_name": "Clay Pellets (LECA)", "is_group": 0,
     "parent_item_group": "Growing Media"},
]

cropcategories = [
    {"category_name": "Cereals", "category_description":
        "This category includes crops like wheat, rice, corn (maize), barley, oats, and millets. Cereals are primarily grown for their edible grains, which are rich in carbohydrates and form the staple food for many societies."},
    {"category_name": "Pulses/Legumes", "category_description": "Pulses comprise crops like beans, lentils, chickpeas, and peas. They are valued for their high protein content and are an essential source of nutrition, especially in vegetarian diets."},
    {"category_name": "Oilseeds", "category_description": "Oilseeds include crops like soybeans, sunflower, canola, and sesame. These crops are cultivated primarily for the extraction of oil from their seeds, which is used in cooking, food processing, and various industrial applications."},
    {"category_name": "Fruits and Vegetables", "category_description": "This category encompasses a wide range of crops, including apples, oranges, tomatoes, carrots, and lettuce. Fruits and vegetables are rich sources of essential vitamins, minerals, and dietary fiber."},
    {"category_name": "Roots and Tubers", "category_description": "This category includes crops like potatoes, sweet potatoes, cassava, and yams. These plants store energy in their underground parts, making them important sources of carbohydrates in many diets."},
    {"category_name": "Cash Crops", "category_description": "Cash crops are grown primarily for sale and profit rather than for personal consumption. Examples include cotton, coffee, cocoa, tea, and tobacco."},
    {"category_name": "Fiber Crops", "category_description":
     "Fiber crops are cultivated for their fibers, which are used in various industries. Cotton is a prime example of a fiber crop."},
    {"category_name": "Forage and Fodder Crops", "category_description":
     "These crops, such as alfalfa, clover, and various grasses, are grown to provide feed for livestock."},
    {"category_name": "Medicinal and Aromatic Plants (MAPs)", "category_description":
     "These crops, like aloe vera, lavender, and mint, are cultivated for their medicinal or aromatic properties and are used in various industries, including pharmaceuticals and perfumery."},
    {"category_name": "Industrial Crops", "category_description":
     "Industrial crops include plants like sugarcane (for sugar and biofuel production), rubber trees (for natural rubber), and hemp (for fibers and various industrial applications)."},
    {"category_name": "Spices and Herbs", "category_description":
     "This category includes crops like pepper, basil, oregano, and turmeric. Spices and herbs are used to flavor food and for their medicinal properties."},
    {"category_name": "Spices and Herbs", "category_description":
     "Crops like tea, coffee, and cacao are grown for the production of beverages."},
    {"category_name": "Spices and Herbs", "category_description": "This category includes crops that are not widely grown but have unique characteristics or are highly valued. Examples include truffles, saffron, and certain exotic fruits."},
]

analysiscriterias = [
    {"title": "Nitrogen Content", "standard": 1, "linked_doctype": "Fertilizer"},
    {"title": "Phosphorous Content", "standard": 1, "linked_doctype": "Fertilizer"},
    {"title": "Potassium Content", "standard": 1, "linked_doctype": "Fertilizer"},
    {"title": "Calcium Content", "standard": 1, "linked_doctype": "Fertilizer"},
    {"title": "Sulphur Content", "standard": 1, "linked_doctype": "Fertilizer"},
    {"title": "Magnesium Content", "standard": 1,
     "linked_doctype": "Fertilizer"},
    {"title": "Iron Content", "standard": 1, "linked_doctype": "Fertilizer"},
    {"title": "Copper Content", "standard": 1, "linked_doctype": "Fertilizer"},
    {"title": "Zinc Content", "standard": 1, "linked_doctype": "Fertilizer"},
    {"title": "Boron Content", "standard": 1, "linked_doctype": "Fertilizer"},
    {"title": "Manganese Content", "standard": 1,
     "linked_doctype": "Fertilizer"},
    {"title": "Chlorine Content", "standard": 1, "linked_doctype": "Fertilizer"},
    {"title": "Molybdenum Content", "standard": 1,
     "linked_doctype": "Fertilizer"},
    {"title": "Sodium Content", "standard": 1, "linked_doctype": "Fertilizer"},
    {"title": "Humic Acid", "standard": 1, "linked_doctype": "Fertilizer"},
    {"title": "Fulvic Acid", "standard": 1, "linked_doctype": "Fertilizer"},
    {"title": "Inert", "standard": 1, "linked_doctype": "Fertilizer"},
    {"title": "Others", "standard": 1, "linked_doctype": "Fertilizer"},
    {"title": "Nitrogen", "standard": 1, "linked_doctype": "Plant Analysis"},
    {"title": "Phosphorous", "standard": 1,
     "linked_doctype": "Plant Analysis"},
    {"title": "Potassium", "standard": 1, "linked_doctype": "Plant Analysis"},
    {"title": "Calcium", "standard": 1, "linked_doctype": "Plant Analysis"},
    {"title": "Magnesium", "standard": 1, "linked_doctype": "Plant Analysis"},
    {"title": "Sulphur", "standard": 1, "linked_doctype": "Plant Analysis"},
    {"title": "Boron", "standard": 1, "linked_doctype": "Plant Analysis"},
    {"title": "Copper", "standard": 1, "linked_doctype": "Plant Analysis"},
    {"title": "Iron", "standard": 1, "linked_doctype": "Plant Analysis"},
    {"title": "Manganese", "standard": 1, "linked_doctype": "Plant Analysis"},
    {"title": "Zinc", "standard": 1, "linked_doctype": "Plant Analysis"},
    {"title": "Depth (in cm)", "standard": 1,
     "linked_doctype": "Soil Analysis"},
    {"title": "Soil pH", "standard": 1, "linked_doctype": "Soil Analysis"},
    {"title": "Salt Concentration (%)", "standard": 1,
     "linked_doctype": "Soil Analysis"},
    {"title": "Organic Matter (%)", "standard": 1,
     "linked_doctype": "Soil Analysis"},
    {"title": "CEC (Cation Exchange Capacity) (MAQ/100mL)",
     "standard": 1, "linked_doctype": "Soil Analysis"},
    {"title": "Potassium Saturation (%)", "standard": 1,
     "linked_doctype": "Soil Analysis"},
    {"title": "Calcium Saturation (%)", "standard": 1,
     "linked_doctype": "Soil Analysis"},
    {"title": "Manganese Saturation (%)", "standard": 1,
     "linked_doctype": "Soil Analysis"},
    {"title": "Nirtogen (ppm)", "standard": 1,
     "linked_doctype": "Soil Analysis"},
    {"title": "Phosphorous (ppm)", "standard": 1,
     "linked_doctype": "Soil Analysis"},
    {"title": "Potassium (ppm)", "standard": 1,
     "linked_doctype": "Soil Analysis"},
    {"title": "Calcium (ppm)", "standard": 1,
     "linked_doctype": "Soil Analysis"},
    {"title": "Magnesium (ppm)", "standard": 1,
     "linked_doctype": "Soil Analysis"},
    {"title": "Sulphur (ppm)", "standard": 1,
     "linked_doctype": "Soil Analysis"},
    {"title": "Copper (ppm)", "standard": 1,
     "linked_doctype": "Soil Analysis"},
    {"title": "Iron (ppm)", "standard": 1,
     "linked_doctype": "Soil Analysis"},
    {"title": "Manganese (ppm)", "standard": 1,
     "linked_doctype": "Soil Analysis"},
    {"title": "Zinc (ppm)", "standard": 1,
     "linked_doctype": "Soil Analysis"},
    {"title": "Aluminium (ppm)", "standard": 1,
     "linked_doctype": "Soil Analysis"},
    {"title": "Water pH", "standard": 1, "linked_doctype": "Water Analysis"},
    {"title": "Conductivity (mS/cm)", "standard": 1,
     "linked_doctype": "Water Analysis"},
    {"title": "Hardness (mg/CaCO3)", "standard": 1,
     "linked_doctype": "Water Analysis"},
    {"title": "Turbidity (NTU)", "standard": 1,
     "linked_doctype": "Water Analysis"},
    {"title": "Odor", "standard": 1, "linked_doctype": "Water Analysis"},
    {"title": "Color", "standard": 1, "linked_doctype": "Water Analysis"},
    {"title": "Nitrate (mg/L)", "standard": 1,
     "linked_doctype": "Water Analysis"},
    {"title": "Nirtite (mg/L)", "standard": 1,
     "linked_doctype": "Water Analysis"},
    {"title": "Calcium (mg/L)", "standard": 1,
     "linked_doctype": "Water Analysis"},
    {"title": "Magnesium (mg/L)", "standard": 1,
     "linked_doctype": "Water Analysis"},
    {"title": "Sulphate (mg/L)", "standard": 1,
     "linked_doctype": "Water Analysis"},
    {"title": "Boron (mg/L)", "standard": 1,
     "linked_doctype": "Water Analysis"},
    {"title": "Copper (mg/L)", "standard": 1,
     "linked_doctype": "Water Analysis"},
    {"title": "Iron (mg/L)", "standard": 1,
     "linked_doctype": "Water Analysis"},
    {"title": "Manganese (mg/L)", "standard": 1,
     "linked_doctype": "Water Analysis"},
    {"title": "Zinc (mg/L)", "standard": 1,
     "linked_doctype": "Water Analysis"},
    {"title": "Chlorine (mg/L)", "standard": 1,
     "linked_doctype": "Water Analysis"},
    {"title": "Bulk Density", "standard": 1, "linked_doctype": "Soil Texture"},
    {"title": "Field Capacity", "standard": 1,
     "linked_doctype": "Soil Texture"},
    {"title": "Wilting Point", "standard": 1,
     "linked_doctype": "Soil Texture"},
    {"title": "Hydraulic Conductivity", "standard": 1,
     "linked_doctype": "Soil Texture"},
    {"title": "Organic Matter", "standard": 1,
     "linked_doctype": "Soil Texture"},
    {"title": "Temperature High", "standard": 1, "linked_doctype": "Weather"},
    {"title": "Temperature Low", "standard": 1, "linked_doctype": "Weather"},
    {"title": "Temperature Average", "standard": 1, "linked_doctype": "Weather"},
    {"title": "Dew Point", "standard": 1, "linked_doctype": "Weather"},
    {"title": "Precipitation Received",
     "standard": 1, "linked_doctype": "Weather"},
    {"title": "Humidity", "standard": 1, "linked_doctype": "Weather"},
    {"title": "Pressure", "standard": 1, "linked_doctype": "Weather"},
    {"title": "Insolation/ PAR (Photosynthetically Active Radiation)",
     "standard": 1, "linked_doctype": "Weather"},
    {"title": "Degree Days", "standard": 1, "linked_doctype": "Weather"},
]

livestock_species = [
    {"species_name": "Cattle", "scientific_name": "Bos taurus",
        "gestation_period_days": 283, "default_item_group": "Cattle"},
    {"species_name": "Buffalo", "scientific_name": "Bubalus bubalis",
        "gestation_period_days": 310, "default_item_group": "Buffalo"},
    {"species_name": "Sheep", "scientific_name": "Ovis aries",
        "gestation_period_days": 152, "default_item_group": "Sheep"},
    {"species_name": "Goat", "scientific_name": "Capra hircus",
        "gestation_period_days": 150, "default_item_group": "Goat"},
    {"species_name": "Horse", "scientific_name": "Equus ferus caballus",
        "gestation_period_days": 340, "default_item_group": "Horse"},
    {"species_name": "Camel (Dromedary)", "scientific_name": "Camelus dromedarius",
     "gestation_period_days": 390, "default_item_group": "Camel"},
    {"species_name": "Camel (Bactrian)", "scientific_name": "Camelus bactrianus",
     "gestation_period_days": 410, "default_item_group": "Camel"},
    {"species_name": "Rabbit", "scientific_name": "Oryctolagus cuniculus",
        "gestation_period_days": 31, "default_item_group": "Rabbit"},
    {"species_name": "Chicken", "scientific_name": "Gallus gallus domesticus",
        "gestation_period_days": 21, "default_item_group": "Chicken"},
    {"species_name": "Duck", "scientific_name": "Anas platyrhynchos domesticus",
        "gestation_period_days": 28, "default_item_group": "Duck"},
    {"species_name": "Goose", "scientific_name": "Anser anser domesticus",
        "gestation_period_days": 30, "default_item_group": "Goose"},
    {"species_name": "Turkey", "scientific_name": "Meleagris gallopavo",
        "gestation_period_days": 28, "default_item_group": "Turkey"},
]
livestock_breeds_tunisia = [
    # Cattle
    {"breed_name": "Brune de l’Atlas", "species": "Cattle"},
    {"breed_name": "Holstein Friesian", "species": "Cattle"},
    {"breed_name": "Brown Swiss", "species": "Cattle"},
    {"breed_name": "Tarentaise", "species": "Cattle"},

    # Sheep
    {"breed_name": "Barbarine", "species": "Sheep"},
    {"breed_name": "Queue Fine de l’Ouest", "species": "Sheep"},
    {"breed_name": "Noire de Thibar", "species": "Sheep"},

    # Goat
    {"breed_name": "Local Native Goat", "species": "Goat"},
    {"breed_name": "Alpine Crossbred", "species": "Goat"},
    {"breed_name": "Saanen Crossbred", "species": "Goat"},

    # Poultry
    {"breed_name": "Local Baladi Chicken", "species": "Chicken"},
    {"breed_name": "ISA Brown", "species": "Chicken"},
    {"breed_name": "Lohmann Brown", "species": "Chicken"},
    {"breed_name": "Ross 308", "species": "Chicken"},
    {"breed_name": "Cobb 500", "species": "Chicken"}
]


warehouses = [
    {"warehouse_name": "Agriculture", "is_group": 1, "parent_warehouse": None},
    {"warehouse_name": "Field Crops Storage",
     "is_group": 0, "parent_warehouse": "Agriculture"},
    {"warehouse_name": "Fertilizers & Pesticides",
     "is_group": 0, "parent_warehouse": "Agriculture"},
    {"warehouse_name": "Seeds & Planting Material",
     "is_group": 0, "parent_warehouse": "Agriculture"},

    {"warehouse_name": "Hydroponics", "is_group": 1, "parent_warehouse": None},
    {"warehouse_name": "Nutrient Solutions",
     "is_group": 0, "parent_warehouse": "Hydroponics"},
    {"warehouse_name": "Growing Media", "is_group": 0,
     "parent_warehouse": "Hydroponics"},

    {"warehouse_name": "Livestock", "is_group": 1, "parent_warehouse": None},
    {"warehouse_name": "Cattle Barn", "is_group": 1,
     "parent_warehouse": "Livestock"},
    {"warehouse_name": "Cattle Pen 1", "is_group": 0,
     "parent_warehouse": "Cattle Barn"},
    {"warehouse_name": "Cattle Pen 2", "is_group": 0,
     "parent_warehouse": "Cattle Barn"},
    {"warehouse_name": "Poultry House", "is_group": 1,
     "parent_warehouse": "Livestock"},
    {"warehouse_name": "Broilers", "is_group": 0,
     "parent_warehouse": "Poultry House"},
    {"warehouse_name": "Layers", "is_group": 0,
     "parent_warehouse": "Poultry House"},
    {"warehouse_name": "Grazing Zones", "is_group": 1,
     "parent_warehouse": "Livestock"},
    {"warehouse_name": "Pasture 1", "is_group": 0,
     "parent_warehouse": "Grazing Zones"},
    {"warehouse_name": "Pasture 2", "is_group": 0,
     "parent_warehouse": "Grazing Zones"},
    {"warehouse_name": "Feed Storage", "is_group": 0,
     "parent_warehouse": "Livestock"},
    {"warehouse_name": "Medicine & Vaccines",
     "is_group": 0, "parent_warehouse": "Livestock"},
]


group_types_to_create = [
    # --- Breeding & Young Stock ---
    {"main_group_type": "Breeding & Young Stock",
        "group_type_name": "Breeding Stock"},
    {"main_group_type": "Breeding & Young Stock",
        "group_type_name": "Bull / Ram / Boar Pen"},
    {"main_group_type": "Breeding & Young Stock",
        "group_type_name": "Dry Cow / Ewe Group"},
    {"main_group_type": "Breeding & Young Stock",
        "group_type_name": "Replacement Heifers / Gilts"},
    {"main_group_type": "Breeding & Young Stock",
        "group_type_name": "Calf / Lambing / Piglet Pen"},
    {"main_group_type": "Breeding & Young Stock",
        "group_type_name": "Nursery Group"},
    {"main_group_type": "Breeding & Young Stock", "group_type_name": "Weaning Pen"},

    # --- Production ---
    {"main_group_type": "Production", "group_type_name": "Dairy Production"},
    {"main_group_type": "Production", "group_type_name": "Grower Group"},
    {"main_group_type": "Production", "group_type_name": "Fattening / Finishing"},
    {"main_group_type": "Production", "group_type_name": "Free Range Flock"},

    # --- Health & Status ---
    {"main_group_type": "Health & Status", "group_type_name": "Quarantine"},
    {"main_group_type": "Health & Status", "group_type_name": "Hospital Pen"},
    {"main_group_type": "Health & Status", "group_type_name": "Transition Group"},
    {"main_group_type": "Health & Status", "group_type_name": "Cull Group"},
]
