import frappe
from frappe import _

itemgroups = [
        {"item_group_name":"Agriculture Items Group","is_group":1},
        {"item_group_name":"Fertilizer","is_group":0,"parent_item_group":"Agriculture Items Group"},
		{"item_group_name":"Seeds","is_group":0,"parent_item_group":"Agriculture Items Group"},
        {"item_group_name":"By Product","is_group":0,"parent_item_group":"Agriculture Items Group"},
        {"item_group_name":"Produce","is_group":0,"parent_item_group":"Agriculture Items Group"},
        ]

cropcategories = [
        {"category_name":"Cereals","category_description":"This category includes crops like wheat, rice, corn (maize), barley, oats, and millets. Cereals are primarily grown for their edible grains, which are rich in carbohydrates and form the staple food for many societies."},
        {"category_name":"Pulses/Legumes","category_description":"Pulses comprise crops like beans, lentils, chickpeas, and peas. They are valued for their high protein content and are an essential source of nutrition, especially in vegetarian diets."},
        {"category_name":"Oilseeds","category_description":"Oilseeds include crops like soybeans, sunflower, canola, and sesame. These crops are cultivated primarily for the extraction of oil from their seeds, which is used in cooking, food processing, and various industrial applications."},
        {"category_name":"Fruits and Vegetables","category_description":"This category encompasses a wide range of crops, including apples, oranges, tomatoes, carrots, and lettuce. Fruits and vegetables are rich sources of essential vitamins, minerals, and dietary fiber."},
        {"category_name":"Roots and Tubers","category_description":"This category includes crops like potatoes, sweet potatoes, cassava, and yams. These plants store energy in their underground parts, making them important sources of carbohydrates in many diets."},
        {"category_name":"Cash Crops","category_description":"Cash crops are grown primarily for sale and profit rather than for personal consumption. Examples include cotton, coffee, cocoa, tea, and tobacco."},
        {"category_name":"Fiber Crops","category_description":"Fiber crops are cultivated for their fibers, which are used in various industries. Cotton is a prime example of a fiber crop."},
        {"category_name":"Forage and Fodder Crops","category_description":"These crops, such as alfalfa, clover, and various grasses, are grown to provide feed for livestock."},
        {"category_name":"Medicinal and Aromatic Plants (MAPs)","category_description":"These crops, like aloe vera, lavender, and mint, are cultivated for their medicinal or aromatic properties and are used in various industries, including pharmaceuticals and perfumery."},
        {"category_name":"Industrial Crops","category_description":"Industrial crops include plants like sugarcane (for sugar and biofuel production), rubber trees (for natural rubber), and hemp (for fibers and various industrial applications)."},
        {"category_name":"Spices and Herbs","category_description":"This category includes crops like pepper, basil, oregano, and turmeric. Spices and herbs are used to flavor food and for their medicinal properties."},
        {"category_name":"Spices and Herbs","category_description":"Crops like tea, coffee, and cacao are grown for the production of beverages."},
        {"category_name":"Spices and Herbs","category_description":"This category includes crops that are not widely grown but have unique characteristics or are highly valued. Examples include truffles, saffron, and certain exotic fruits."},
        ]

analysiscriterias = [
        {"title":"Nitrogen Content","standard":1,"linked_doctype":"Fertilizer"},
		{"title":"Phosphorous Content","standard":1,"linked_doctype":"Fertilizer"},
		{"title":"Potassium Content","standard":1,"linked_doctype":"Fertilizer"},
        {"title":"Calcium Content","standard":1,"linked_doctype":"Fertilizer"},
        {"title":"Sulphur Content","standard":1,"linked_doctype":"Fertilizer"},
        {"title":"Magnesium Content","standard":1,"linked_doctype":"Fertilizer"},
        {"title":"Iron Content","standard":1,"linked_doctype":"Fertilizer"},
        {"title":"Copper Content","standard":1,"linked_doctype":"Fertilizer"},
        {"title":"Zinc Content","standard":1,"linked_doctype":"Fertilizer"},
        {"title":"Boron Content","standard":1,"linked_doctype":"Fertilizer"},
        {"title":"Manganese Content","standard":1,"linked_doctype":"Fertilizer"},
        {"title":"Chlorine Content","standard":1,"linked_doctype":"Fertilizer"},
        {"title":"Molybdenum Content","standard":1,"linked_doctype":"Fertilizer"},
        {"title":"Sodium Content","standard":1,"linked_doctype":"Fertilizer"},
        {"title":"Humic Acid","standard":1,"linked_doctype":"Fertilizer"},
        {"title":"Fulvic Acid","standard":1,"linked_doctype":"Fertilizer"},
        {"title":"Inert","standard":1,"linked_doctype":"Fertilizer"},
        {"title":"Others","standard":1,"linked_doctype":"Fertilizer"},
        {"title":"Nitrogen","standard":1,"linked_doctype":"Plant Analysis"},
        {"title":"Phosphorous","standard":1,"linked_doctype":"Plant Analysis"},
        {"title":"Potassium","standard":1,"linked_doctype":"Plant Analysis"},
        {"title":"Calcium","standard":1,"linked_doctype":"Plant Analysis"},
        {"title":"Magnesium","standard":1,"linked_doctype":"Plant Analysis"},
        {"title":"Sulphur","standard":1,"linked_doctype":"Plant Analysis"},
        {"title":"Boron","standard":1,"linked_doctype":"Plant Analysis"},
        {"title":"Copper","standard":1,"linked_doctype":"Plant Analysis"},
        {"title":"Iron","standard":1,"linked_doctype":"Plant Analysis"},
        {"title":"Manganese","standard":1,"linked_doctype":"Plant Analysis"},
        {"title":"Zinc","standard":1,"linked_doctype":"Plant Analysis"},
        {"title":"Depth (in cm}","standard":1,"linked_doctype":"Soil Analysis"},
        {"title":"Soil pH","standard":1,"linked_doctype":"Soil Analysis"},
        {"title":"Salt Concentration (%}","standard":1,"linked_doctype":"Soil Analysis"},
        {"title":"Organic Matter (%}","standard":1,"linked_doctype":"Soil Analysis"},
        {"title":"CEC (Cation Exchange Capacity} (MAQ/100mL}","standard":1,"linked_doctype":"Soil Analysis"},
        {"title":"Potassium Saturation (%}","standard":1,"linked_doctype":"Soil Analysis"},
        {"title":"Calcium Saturation (%}","standard":1,"linked_doctype":"Soil Analysis"},
        {"title":"Manganese Saturation (%}","standard":1,"linked_doctype":"Soil Analysis"},
        {"title":"Nirtogen (ppm}","standard":1,"linked_doctype":"Soil Analysis"},
        {"title":"Phosphorous (ppm}","standard":1,"linked_doctype":"Soil Analysis"},
        {"title":"Potassium (ppm}","standard":1,"linked_doctype":"Soil Analysis"},
        {"title":"Calcium (ppm}","standard":1,"linked_doctype":"Soil Analysis"},
        {"title":"Magnesium (ppm}","standard":1,"linked_doctype":"Soil Analysis"},
        {"title":"Sulphur (ppm}","standard":1,"linked_doctype":"Soil Analysis"},
        {"title":"Copper (ppm}","standard":1,"linked_doctype":"Soil Analysis"},
        {"title":"Iron (ppm}","standard":1,"linked_doctype":"Soil Analysis"},
        {"title":"Manganese (ppm}","standard":1,"linked_doctype":"Soil Analysis"},
        {"title":"Zinc (ppm}","standard":1,"linked_doctype":"Soil Analysis"},
        {"title":"Aluminium (ppm}","standard":1,"linked_doctype":"Soil Analysis"},
        {"title":"Water pH","standard":1,"linked_doctype":"Water Analysis"},
        {"title":"Conductivity (mS/cm}","standard":1,"linked_doctype":"Water Analysis"},
        {"title":"Hardness (mg/CaCO3}","standard":1,"linked_doctype":"Water Analysis"},
        {"title":"Turbidity (NTU}","standard":1,"linked_doctype":"Water Analysis"},
        {"title":"Odor","standard":1,"linked_doctype":"Water Analysis"},
        {"title":"Color","standard":1,"linked_doctype":"Water Analysis"},
        {"title":"Nitrate (mg/L}","standard":1,"linked_doctype":"Water Analysis"},
        {"title":"Nirtite (mg/L}","standard":1,"linked_doctype":"Water Analysis"},
        {"title":"Calcium (mg/L}","standard":1,"linked_doctype":"Water Analysis"},
        {"title":"Magnesium (mg/L}","standard":1,"linked_doctype":"Water Analysis"},
        {"title":"Sulphate (mg/L}","standard":1,"linked_doctype":"Water Analysis"},
        {"title":"Boron (mg/L}","standard":1,"linked_doctype":"Water Analysis"},
        {"title":"Copper (mg/L}","standard":1,"linked_doctype":"Water Analysis"},
        {"title":"Iron (mg/L}","standard":1,"linked_doctype":"Water Analysis"},
        {"title":"Manganese (mg/L}","standard":1,"linked_doctype":"Water Analysis"},
        {"title":"Zinc (mg/L}","standard":1,"linked_doctype":"Water Analysis"},
        {"title":"Chlorine (mg/L}","standard":1,"linked_doctype":"Water Analysis"},
        {"title":"Bulk Density","standard":1,"linked_doctype":"Soil Texture"},
        {"title":"Field Capacity","standard":1,"linked_doctype":"Soil Texture"},
        {"title":"Wilting Point","standard":1,"linked_doctype":"Soil Texture"},
        {"title":"Hydraulic Conductivity","standard":1,"linked_doctype":"Soil Texture"},
        {"title":"Organic Matter","standard":1,"linked_doctype":"Soil Texture"},
        {"title":"Temperature High","standard":1,"linked_doctype":"Weather"},
        {"title":"Temperature Low","standard":1,"linked_doctype":"Weather"},
        {"title":"Temperature Average","standard":1,"linked_doctype":"Weather"},
        {"title":"Dew Point","standard":1,"linked_doctype":"Weather"},
        {"title":"Precipitation Received","standard":1,"linked_doctype":"Weather"},
        {"title":"Humidity","standard":1,"linked_doctype":"Weather"},
        {"title":"Pressure","standard":1,"linked_doctype":"Weather"},
        {"title":"Insolation/ PAR (Photosynthetically Active Radiation}","standard":1,"linked_doctype":"Weather"},
        {"title":"Degree Days","standard":1,"linked_doctype":"Weather"},    
    ]